[dependencies]
actix-web = "4.3.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
rand = "0.8.5"
lazy_static = "1.4.0"
tokio = { version = "1.37.0", features = ["full"] }

[[bin]]
name = "generate_positions"
path = "src/bin/generate_positions.rs"