<<<<<<< HEAD
pub mod prelude;
pub mod game;
pub mod player;

// You could also potentially just use the mod.rs generated by sea-orm
// by uncommenting the line below, but explicitly declaring modules
// is often clearer.
// pub mod models; // Assuming the generated mod.rs is named models.rs or is in src/models.rs 
=======
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;

pub mod game;
pub mod player;
>>>>>>> upstream/main
